spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: user
    password: example
    hikari:
      maximum-pool-size: 5
      connection-timeout: 2000 # in ms (default value)

logging:
  level:
    org.springframework: DEBUG
    ch.aaap.engineering.example: DEBUG
    com.zaxxer.hikari: DEBUG