spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: user
    password: example
